apiVersion: v1
kind: Service
metadata:
  name: product-service-lb
  labels:
    app: product-service
  annotations:
    # Azure Load Balancer specific annotations
    service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: "/actuator/health"
    service.beta.kubernetes.io/azure-load-balancer-health-probe-protocol: "http"
    service.beta.kubernetes.io/azure-load-balancer-health-probe-port: "8080"
    service.beta.kubernetes.io/azure-load-balancer-health-probe-interval: "5"
    service.beta.kubernetes.io/azure-load-balancer-health-probe-num-of-probe: "2"
    # Restrict source IP ranges (uncomment and customize for production)
    # service.beta.kubernetes.io/load-balancer-source-ranges: "203.0.113.0/24,198.51.100.0/24"
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: product-service
  # Session affinity for stateful applications (optional)
  sessionAffinity: None
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service-lb
  labels:
    app: inventory-service
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: "/actuator/health"
    service.beta.kubernetes.io/azure-load-balancer-health-probe-protocol: "http"
    service.beta.kubernetes.io/azure-load-balancer-health-probe-port: "8081"
    service.beta.kubernetes.io/azure-load-balancer-health-probe-interval: "5"
    service.beta.kubernetes.io/azure-load-balancer-health-probe-num-of-probe: "2"
spec:
  type: LoadBalancer
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
    name: http
  selector:
    app: inventory-service
  sessionAffinity: None
---
apiVersion: v1
kind: Service
metadata:
  name: order-service-lb
  labels:
    app: order-service
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: "/actuator/health"
    service.beta.kubernetes.io/azure-load-balancer-health-probe-protocol: "http"
    service.beta.kubernetes.io/azure-load-balancer-health-probe-port: "8082"
    service.beta.kubernetes.io/azure-load-balancer-health-probe-interval: "5"
    service.beta.kubernetes.io/azure-load-balancer-health-probe-num-of-probe: "2"
spec:
  type: LoadBalancer
  ports:
  - port: 8082
    targetPort: 8082
    protocol: TCP
    name: http
  selector:
    app: order-service
  sessionAffinity: None 