apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  labels:
    app: mysql
    component: database
type: Opaque
data:
  # Default passwords - CHANGE THESE in production!
  # root-password: base64 encoded "SecureRootPass2024!"
  root-password: U2VjdXJlUm9vdFBhc3MyMDI0IQ==
  # password: base64 encoded "SecureUserPass2024!"
  password: U2VjdXJlVXNlclBhc3MyMDI0IQ==
  # database: base64 encoded "microservices"
  database: bWljcm9zZXJ2aWNlcw==
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  labels:
    app: mongodb
    component: database
type: Opaque
data:
  # Default passwords - CHANGE THESE in production!
  # root-username: base64 encoded "admin"
  root-username: YWRtaW4=
  # root-password: base64 encoded "SecureMongoPass2024!"
  root-password: U2VjdXJlTW9uZ29QYXNzMjAyNCE= 