version: '3.8'

services:
  # CI/CD
  jenkins:
    build:
      context: ..
      dockerfile: Dockerfile.jenkins
    container_name: jenkins-backend
    ports:
      - "31080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/workspace/backend
      - ./k8s:/workspace/k8s
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - MAVEN_HOME=/opt/maven
      - MAVEN_OPTS=-Dmaven.repo.local=/var/jenkins_home/.m2/repository
      - DOCKER_HOST=unix:///var/run/docker.sock
    networks:
      - microservices-network
    restart: unless-stopped

  # Docker Registry for CI/CD
  registry:
    image: registry:2
    container_name: docker-registry-backend
    ports:
      - "32000:5000"
    volumes:
      - registry_data:/var/lib/registry
    networks:
      - microservices-network
    restart: unless-stopped

  # Databases
  mongodb:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db
    networks:
      - microservices-network

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: microservices
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - microservices-network

  # Microservices
  product-service:
    build: ./product-service
    container_name: product-service
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://admin:password@mongodb:27017/product-service?authSource=admin
      EUREKA_CLIENT_ENABLED: false
    depends_on:
      - mongodb
    networks:
      - microservices-network
    restart: unless-stopped

  inventory-service:
    build: ./inventory-service
    container_name: inventory-service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/inventory-service
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      EUREKA_CLIENT_ENABLED: false
    depends_on:
      - mysql
    networks:
      - microservices-network
    restart: unless-stopped

  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/order-service
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      EUREKA_CLIENT_ENABLED: false
    depends_on:
      - mysql
    networks:
      - microservices-network
    restart: unless-stopped

  # Monitoring
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    networks:
      - microservices-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - microservices-network

volumes:
  jenkins_home:
    driver: local
  registry_data:
    driver: local
  mongodb_data:
  mysql_data:
  grafana_data:

networks:
  microservices-network:
    driver: bridge 